### ISSUE TITLE
License and Name

### ISSUE THREAD

**Issue by elijahimmer** [wychwitch/typst-mla9-template#3]
I have a request, well two.
Could you please license this, with MIT or otherwise, so that people can copy and use it without having to worry about it not being licensed. Even a simple template like this should have something because it is still code and licenses still do apply.

Also, if you could fix the spelling of the name, that would be nice.
It would take a moment for the links to fix, but if the name wasn't intentionally misspelled, it would be nice to fix.

Thanks for your time, and I do like the template so far. I would like to contribute to it if you can license it.

**Comment by bluerosegarden** [comment]
Oh hello! I can do both of these! I actually meant for this to be MIT from the beginning.

Also I didn't realize this whole time that I had a typo in the title LMAO, so I'll fix that as well!  Thanks for letting me know

**Comment by wychwitch** [comment]
Oh hello! I can do both of these! I actually meant for this to be MIT from the beginning.

Also I didn't realize this whole time that I had a typo in the title LMAO, so I'll fix that as well!  Thanks for letting me know

**Comment by wychwitch** [comment]
both are done! I look forward to any contributions you may make ^^
